### ISSUE TITLE
Tiger?

### ISSUE THREAD

**Issue by rburchell** [a-e-k/canvas_ity#6]
You mention in https://github.com/a-e-k/canvas_ity/issues/4#issuecomment-1411671353 that you have the tiger ported.. I just wonder if there's a copy of that available anywhere? Curious to see how a bigger example looks (and what the performance bottlenecks look like) :)

Thanks for the cool code, nice work!

**Comment by a-e-k** [comment]
Thanks!

It's not checked into the repo, but I do still have that.  Now that you've prompted me, I'm sprucing it up (writing a CMake file, adding some comments on the origin and conversion process, etc.) and should have it posted here in a day or two.

**Comment by rburchell** [comment]
>should have it posted here in a day or two.

No rush of course, this is entirely just to exercise my curiosity. But thanks a lot whenever you manage to get around to it! :)

> I'm not sure how representative it is performance-wise since it only uses a fraction of the features and API

That's always going to be a fun question about an open ended API like this, right? What's "representative" is entirely dependent on which features you exercise, which in turn depends on what you're actually trying to display, heh.. :)

**Comment by a-e-k** [comment]
See `demos/tiger/`.
